/*
 * ******************************************************************************
 * @file           : ProductsApplication.java
 * @author         : Automatically generated by IntelliJ IDEA IDE.
 * @brief          : Starting point of the `ProductsApplication` app.
 * ******************************************************************************
 */

package com.example.products;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class ProductsApplication {

    public static void main(String[] args) {
        SpringApplication.run(ProductsApplication.class, args);
    }
    
}
